// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScholaAi.Models;

#nullable disable

namespace ScholaAi.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20251128220127_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScholaAi.Models.adminLogs", b =>
                {
                    b.Property<int>("logId")
                        .HasColumnType("int");

                    b.Property<int>("adminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("targetRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("targetType")
                        .HasColumnType("int");

                    b.Property<int?>("targetUserId")
                        .HasColumnType("int");

                    b.HasKey("logId");

                    b.HasIndex("targetRequestId")
                        .IsUnique()
                        .HasFilter("[targetRequestId] IS NOT NULL");

                    b.HasIndex("targetUserId")
                        .IsUnique()
                        .HasFilter("[targetUserId] IS NOT NULL");

                    b.ToTable("adminLogs");
                });

            modelBuilder.Entity("ScholaAi.Models.chatMessage", b =>
                {
                    b.Property<int>("messageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("messageId"));

                    b.Property<string>("attachmentURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isRead")
                        .HasColumnType("bit");

                    b.Property<string>("messageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("receiverId")
                        .HasColumnType("int");

                    b.Property<int>("senderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("sentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("messageId");

                    b.HasIndex("receiverId");

                    b.HasIndex("senderId");

                    b.ToTable("chatMessages");
                });

            modelBuilder.Entity("ScholaAi.Models.notification", b =>
                {
                    b.Property<int>("notificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notificationId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isRead")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("receiverId")
                        .HasColumnType("int");

                    b.Property<int>("senderId")
                        .HasColumnType("int");

                    b.Property<int>("sessionId")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("notificationId");

                    b.HasIndex("receiverId");

                    b.HasIndex("senderId");

                    b.HasIndex("sessionId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("ScholaAi.Models.rating", b =>
                {
                    b.Property<int>("ratingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ratingId"));

                    b.Property<int>("ratingValue")
                        .HasColumnType("int");

                    b.Property<int>("sessionId")
                        .HasColumnType("int");

                    b.Property<int>("teacherId")
                        .HasColumnType("int");

                    b.HasKey("ratingId");

                    b.HasIndex("sessionId")
                        .IsUnique();

                    b.HasIndex("teacherId");

                    b.ToTable("ratings");
                });

            modelBuilder.Entity("ScholaAi.Models.requestBroadcast", b =>
                {
                    b.Property<int>("broadcastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("broadcastId"));

                    b.Property<bool>("isAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("isDelivered")
                        .HasColumnType("bit");

                    b.Property<int>("requestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("sentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("teacherId")
                        .HasColumnType("int");

                    b.HasKey("broadcastId");

                    b.HasIndex("requestId");

                    b.HasIndex("teacherId");

                    b.ToTable("requestBroadcasts");
                });

            modelBuilder.Entity("ScholaAi.Models.session", b =>
                {
                    b.Property<int>("sessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sessionId"));

                    b.Property<long>("recordedSession")
                        .HasColumnType("bigint");

                    b.Property<int>("requestId")
                        .HasColumnType("int");

                    b.Property<int>("studentId")
                        .HasColumnType("int");

                    b.Property<string>("summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("teacherId")
                        .HasColumnType("int");

                    b.HasKey("sessionId");

                    b.HasIndex("requestId")
                        .IsUnique();

                    b.HasIndex("studentId");

                    b.HasIndex("teacherId");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("ScholaAi.Models.sessionRequest", b =>
                {
                    b.Property<int>("sessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sessionId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("finalScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("preferredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("studentId")
                        .HasColumnType("int");

                    b.Property<int>("subjectId")
                        .HasColumnType("int");

                    b.Property<int?>("teacherId")
                        .HasColumnType("int");

                    b.HasKey("sessionId");

                    b.HasIndex("studentId");

                    b.HasIndex("subjectId")
                        .IsUnique();

                    b.HasIndex("teacherId");

                    b.ToTable("sessionRequests");
                });

            modelBuilder.Entity("ScholaAi.Models.student", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<int>("grade")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.ToTable("students");
                });

            modelBuilder.Entity("ScholaAi.Models.subject", b =>
                {
                    b.Property<int>("subjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("subjectId"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subjectId");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("ScholaAi.Models.teacher", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<string>("certificate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("college")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("totalHoursTaught")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("totalRates")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("userId");

                    b.ToTable("teachers");
                });

            modelBuilder.Entity("ScholaAi.Models.teacherSubject", b =>
                {
                    b.Property<int>("subjectId")
                        .HasColumnType("int");

                    b.Property<int>("teacherId")
                        .HasColumnType("int");

                    b.HasKey("subjectId", "teacherId");

                    b.HasIndex("teacherId");

                    b.ToTable("teacherSubjects");
                });

            modelBuilder.Entity("ScholaAi.Models.transaction", b =>
                {
                    b.Property<int>("transactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transactionId"));

                    b.Property<decimal>("amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("fromWalletId")
                        .HasColumnType("int");

                    b.Property<decimal>("platformFee")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("sessionId")
                        .HasColumnType("int");

                    b.Property<int>("toWalletId")
                        .HasColumnType("int");

                    b.HasKey("transactionId");

                    b.HasIndex("fromWalletId");

                    b.HasIndex("sessionId")
                        .IsUnique();

                    b.HasIndex("toWalletId");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("ScholaAi.Models.user", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("profilePhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("userType")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("userName")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("ScholaAi.Models.wallet", b =>
                {
                    b.Property<int>("walletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("walletId"));

                    b.Property<decimal>("balance")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("walletId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("wallets");
                });

            modelBuilder.Entity("ScholaAi.Models.adminLogs", b =>
                {
                    b.HasOne("ScholaAi.Models.user", "admin")
                        .WithMany("admins")
                        .HasForeignKey("logId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.sessionRequest", "targetReruest")
                        .WithOne("adminLogs")
                        .HasForeignKey("ScholaAi.Models.adminLogs", "targetRequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ScholaAi.Models.user", "target")
                        .WithOne("adminLogs")
                        .HasForeignKey("ScholaAi.Models.adminLogs", "targetUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("admin");

                    b.Navigation("target");

                    b.Navigation("targetReruest");
                });

            modelBuilder.Entity("ScholaAi.Models.chatMessage", b =>
                {
                    b.HasOne("ScholaAi.Models.user", "receiver")
                        .WithMany("receivedMessages")
                        .HasForeignKey("receiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.user", "sender")
                        .WithMany("sentMessages")
                        .HasForeignKey("senderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("receiver");

                    b.Navigation("sender");
                });

            modelBuilder.Entity("ScholaAi.Models.notification", b =>
                {
                    b.HasOne("ScholaAi.Models.user", "receiver")
                        .WithMany("receivedNotifications")
                        .HasForeignKey("receiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.user", "sender")
                        .WithMany("sentNotifications")
                        .HasForeignKey("senderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.session", "sessionNotification")
                        .WithMany("notifications")
                        .HasForeignKey("sessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("receiver");

                    b.Navigation("sender");

                    b.Navigation("sessionNotification");
                });

            modelBuilder.Entity("ScholaAi.Models.rating", b =>
                {
                    b.HasOne("ScholaAi.Models.session", "session")
                        .WithOne("rating")
                        .HasForeignKey("ScholaAi.Models.rating", "sessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.teacher", "teacher")
                        .WithMany("ratings")
                        .HasForeignKey("teacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("session");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("ScholaAi.Models.requestBroadcast", b =>
                {
                    b.HasOne("ScholaAi.Models.sessionRequest", "teacherSession")
                        .WithMany("requestBroadcasts")
                        .HasForeignKey("requestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.teacher", "teacher")
                        .WithMany("requestBroadcasts")
                        .HasForeignKey("teacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("teacher");

                    b.Navigation("teacherSession");
                });

            modelBuilder.Entity("ScholaAi.Models.session", b =>
                {
                    b.HasOne("ScholaAi.Models.sessionRequest", "sessionRequest")
                        .WithOne("session")
                        .HasForeignKey("ScholaAi.Models.session", "requestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.student", "student")
                        .WithMany("sessions")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.teacher", "teacher")
                        .WithMany("sessions")
                        .HasForeignKey("teacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("sessionRequest");

                    b.Navigation("student");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("ScholaAi.Models.sessionRequest", b =>
                {
                    b.HasOne("ScholaAi.Models.student", "student")
                        .WithMany("requests")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.subject", "subject")
                        .WithOne("sessionRequest")
                        .HasForeignKey("ScholaAi.Models.sessionRequest", "subjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.teacher", "teacher")
                        .WithMany("sessionRequests")
                        .HasForeignKey("teacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("student");

                    b.Navigation("subject");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("ScholaAi.Models.student", b =>
                {
                    b.HasOne("ScholaAi.Models.user", "user")
                        .WithOne("student")
                        .HasForeignKey("ScholaAi.Models.student", "userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ScholaAi.Models.teacher", b =>
                {
                    b.HasOne("ScholaAi.Models.user", "user")
                        .WithOne("teacher")
                        .HasForeignKey("ScholaAi.Models.teacher", "userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ScholaAi.Models.teacherSubject", b =>
                {
                    b.HasOne("ScholaAi.Models.subject", "subject")
                        .WithMany("teacherSubjects")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.teacher", "teacher")
                        .WithMany("teacherSubjects")
                        .HasForeignKey("teacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("subject");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("ScholaAi.Models.transaction", b =>
                {
                    b.HasOne("ScholaAi.Models.wallet", "fromWallet")
                        .WithMany("transactionsFrom")
                        .HasForeignKey("fromWalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.session", "session")
                        .WithOne("transaction")
                        .HasForeignKey("ScholaAi.Models.transaction", "sessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.wallet", "toWallet")
                        .WithMany("transactionsTo")
                        .HasForeignKey("toWalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("fromWallet");

                    b.Navigation("session");

                    b.Navigation("toWallet");
                });

            modelBuilder.Entity("ScholaAi.Models.wallet", b =>
                {
                    b.HasOne("ScholaAi.Models.user", "user")
                        .WithOne("wallet")
                        .HasForeignKey("ScholaAi.Models.wallet", "userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ScholaAi.Models.session", b =>
                {
                    b.Navigation("notifications");

                    b.Navigation("rating");

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("ScholaAi.Models.sessionRequest", b =>
                {
                    b.Navigation("adminLogs");

                    b.Navigation("requestBroadcasts");

                    b.Navigation("session");
                });

            modelBuilder.Entity("ScholaAi.Models.student", b =>
                {
                    b.Navigation("requests");

                    b.Navigation("sessions");
                });

            modelBuilder.Entity("ScholaAi.Models.subject", b =>
                {
                    b.Navigation("sessionRequest");

                    b.Navigation("teacherSubjects");
                });

            modelBuilder.Entity("ScholaAi.Models.teacher", b =>
                {
                    b.Navigation("ratings");

                    b.Navigation("requestBroadcasts");

                    b.Navigation("sessionRequests");

                    b.Navigation("sessions");

                    b.Navigation("teacherSubjects");
                });

            modelBuilder.Entity("ScholaAi.Models.user", b =>
                {
                    b.Navigation("adminLogs");

                    b.Navigation("admins");

                    b.Navigation("receivedMessages");

                    b.Navigation("receivedNotifications");

                    b.Navigation("sentMessages");

                    b.Navigation("sentNotifications");

                    b.Navigation("student");

                    b.Navigation("teacher");

                    b.Navigation("wallet");
                });

            modelBuilder.Entity("ScholaAi.Models.wallet", b =>
                {
                    b.Navigation("transactionsFrom");

                    b.Navigation("transactionsTo");
                });
#pragma warning restore 612, 618
        }
    }
}
