// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScholaAi.Models;

#nullable disable

namespace ScholaAi.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20260202192238_intialClean")]
    partial class intialClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ScholaAi.Models.adminLogs", b =>
                {
                    b.Property<int>("logId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("logId"));

                    b.Property<int>("adminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("targetRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("targetType")
                        .HasColumnType("int");

                    b.Property<int?>("targetUserId")
                        .HasColumnType("int");

                    b.HasKey("logId");

                    b.HasIndex("adminId");

                    b.HasIndex("targetRequestId")
                        .IsUnique()
                        .HasFilter("[targetRequestId] IS NOT NULL");

                    b.HasIndex("targetUserId")
                        .IsUnique()
                        .HasFilter("[targetUserId] IS NOT NULL");

                    b.ToTable("adminLogs");
                });

            modelBuilder.Entity("ScholaAi.Models.applicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ScholaAi.Models.availability", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("TimeSlot")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("availability");
                });

            modelBuilder.Entity("ScholaAi.Models.chatMessage", b =>
                {
                    b.Property<int>("messageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("messageId"));

                    b.Property<string>("attachmentURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isRead")
                        .HasColumnType("bit");

                    b.Property<string>("messageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("receiverId")
                        .HasColumnType("int");

                    b.Property<int>("senderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("sentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("messageId");

                    b.HasIndex("receiverId");

                    b.HasIndex("senderId");

                    b.ToTable("chatMessages");
                });

            modelBuilder.Entity("ScholaAi.Models.notification", b =>
                {
                    b.Property<int>("notificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notificationId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isRead")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("receiverId")
                        .HasColumnType("int");

                    b.Property<int>("senderId")
                        .HasColumnType("int");

                    b.Property<int>("sessionId")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("notificationId");

                    b.HasIndex("receiverId");

                    b.HasIndex("senderId");

                    b.HasIndex("sessionId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("ScholaAi.Models.rating", b =>
                {
                    b.Property<int>("ratingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ratingId"));

                    b.Property<string>("comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ratingValue")
                        .HasColumnType("int");

                    b.Property<int>("sessionId")
                        .HasColumnType("int");

                    b.Property<int?>("studentId")
                        .HasColumnType("int");

                    b.Property<int>("teacherId")
                        .HasColumnType("int");

                    b.HasKey("ratingId");

                    b.HasIndex("sessionId")
                        .IsUnique();

                    b.HasIndex("studentId");

                    b.HasIndex("teacherId");

                    b.ToTable("ratings");
                });

            modelBuilder.Entity("ScholaAi.Models.requestBroadcast", b =>
                {
                    b.Property<int>("broadcastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("broadcastId"));

                    b.Property<bool>("isAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("isDelivered")
                        .HasColumnType("bit");

                    b.Property<int>("requestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("sentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("teacherId")
                        .HasColumnType("int");

                    b.HasKey("broadcastId");

                    b.HasIndex("requestId");

                    b.HasIndex("teacherId");

                    b.ToTable("requestBroadcasts");
                });

            modelBuilder.Entity("ScholaAi.Models.session", b =>
                {
                    b.Property<int>("sessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sessionId"));

                    b.Property<int?>("focusScore")
                        .HasColumnType("int");

                    b.Property<long>("recordedSession")
                        .HasColumnType("bigint");

                    b.Property<int>("requestId")
                        .HasColumnType("int");

                    b.Property<int>("studentId")
                        .HasColumnType("int");

                    b.Property<string>("summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("teacherId")
                        .HasColumnType("int");

                    b.HasKey("sessionId");

                    b.HasIndex("requestId")
                        .IsUnique();

                    b.HasIndex("studentId");

                    b.HasIndex("teacherId");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("ScholaAi.Models.sessionRequest", b =>
                {
                    b.Property<int>("requestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("requestId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("finalScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("preferredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("studentId")
                        .HasColumnType("int");

                    b.Property<int>("subjectId")
                        .HasColumnType("int");

                    b.Property<int?>("teacherId")
                        .HasColumnType("int");

                    b.HasKey("requestId");

                    b.HasIndex("studentId");

                    b.HasIndex("subjectId");

                    b.HasIndex("teacherId");

                    b.ToTable("sessionRequests");
                });

            modelBuilder.Entity("ScholaAi.Models.student", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<decimal>("grade")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("userId");

                    b.ToTable("students");
                });

            modelBuilder.Entity("ScholaAi.Models.subject", b =>
                {
                    b.Property<int>("subjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("subjectId"));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subjectId");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("ScholaAi.Models.teacher", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<string>("certificate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("college")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("subjectId")
                        .HasColumnType("int");

                    b.Property<string>("teachingExperience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("totalHoursTaught")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("totalRates")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("userId");

                    b.HasIndex("subjectId");

                    b.ToTable("teachers");
                });

            modelBuilder.Entity("ScholaAi.Models.transaction", b =>
                {
                    b.Property<int>("transactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transactionId"));

                    b.Property<decimal>("amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("fromWalletId")
                        .HasColumnType("int");

                    b.Property<decimal>("platformFee")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("sessionId")
                        .HasColumnType("int");

                    b.Property<int>("toWalletId")
                        .HasColumnType("int");

                    b.HasKey("transactionId");

                    b.HasIndex("fromWalletId");

                    b.HasIndex("sessionId")
                        .IsUnique();

                    b.HasIndex("toWalletId");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("ScholaAi.Models.user", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("applicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("profilePhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("userType")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("applicationUserId")
                        .IsUnique()
                        .HasFilter("[applicationUserId] IS NOT NULL");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("userName")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("ScholaAi.Models.wallet", b =>
                {
                    b.Property<int>("walletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("walletId"));

                    b.Property<decimal>("balance")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("walletId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("wallets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ScholaAi.Models.applicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ScholaAi.Models.applicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.applicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ScholaAi.Models.applicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScholaAi.Models.adminLogs", b =>
                {
                    b.HasOne("ScholaAi.Models.user", "admin")
                        .WithMany("admins")
                        .HasForeignKey("adminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.sessionRequest", "targetRequest")
                        .WithOne("adminLogs")
                        .HasForeignKey("ScholaAi.Models.adminLogs", "targetRequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ScholaAi.Models.user", "target")
                        .WithOne("adminLogs")
                        .HasForeignKey("ScholaAi.Models.adminLogs", "targetUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("admin");

                    b.Navigation("target");

                    b.Navigation("targetRequest");
                });

            modelBuilder.Entity("ScholaAi.Models.availability", b =>
                {
                    b.HasOne("ScholaAi.Models.user", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ScholaAi.Models.chatMessage", b =>
                {
                    b.HasOne("ScholaAi.Models.user", "receiver")
                        .WithMany("receivedMessages")
                        .HasForeignKey("receiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.user", "sender")
                        .WithMany("sentMessages")
                        .HasForeignKey("senderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("receiver");

                    b.Navigation("sender");
                });

            modelBuilder.Entity("ScholaAi.Models.notification", b =>
                {
                    b.HasOne("ScholaAi.Models.user", "receiver")
                        .WithMany("receivedNotifications")
                        .HasForeignKey("receiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.user", "sender")
                        .WithMany("sentNotifications")
                        .HasForeignKey("senderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.session", "sessionNotification")
                        .WithMany("notifications")
                        .HasForeignKey("sessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("receiver");

                    b.Navigation("sender");

                    b.Navigation("sessionNotification");
                });

            modelBuilder.Entity("ScholaAi.Models.rating", b =>
                {
                    b.HasOne("ScholaAi.Models.session", "session")
                        .WithOne("rating")
                        .HasForeignKey("ScholaAi.Models.rating", "sessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.user", "student")
                        .WithMany()
                        .HasForeignKey("studentId");

                    b.HasOne("ScholaAi.Models.teacher", "teacher")
                        .WithMany("ratings")
                        .HasForeignKey("teacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("session");

                    b.Navigation("student");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("ScholaAi.Models.requestBroadcast", b =>
                {
                    b.HasOne("ScholaAi.Models.sessionRequest", "teacherSession")
                        .WithMany("requestBroadcasts")
                        .HasForeignKey("requestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.teacher", "teacher")
                        .WithMany("requestBroadcasts")
                        .HasForeignKey("teacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("teacher");

                    b.Navigation("teacherSession");
                });

            modelBuilder.Entity("ScholaAi.Models.session", b =>
                {
                    b.HasOne("ScholaAi.Models.sessionRequest", "sessionRequest")
                        .WithOne("session")
                        .HasForeignKey("ScholaAi.Models.session", "requestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.student", "student")
                        .WithMany("sessions")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.teacher", "teacher")
                        .WithMany("sessions")
                        .HasForeignKey("teacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("sessionRequest");

                    b.Navigation("student");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("ScholaAi.Models.sessionRequest", b =>
                {
                    b.HasOne("ScholaAi.Models.student", "student")
                        .WithMany("requests")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.subject", "subject")
                        .WithMany("sessionRequests")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.teacher", "teacher")
                        .WithMany("sessionRequests")
                        .HasForeignKey("teacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("student");

                    b.Navigation("subject");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("ScholaAi.Models.student", b =>
                {
                    b.HasOne("ScholaAi.Models.user", "user")
                        .WithOne("student")
                        .HasForeignKey("ScholaAi.Models.student", "userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ScholaAi.Models.teacher", b =>
                {
                    b.HasOne("ScholaAi.Models.subject", "subject")
                        .WithMany("teachers")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.user", "user")
                        .WithOne("teacher")
                        .HasForeignKey("ScholaAi.Models.teacher", "userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("subject");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ScholaAi.Models.transaction", b =>
                {
                    b.HasOne("ScholaAi.Models.wallet", "fromWallet")
                        .WithMany("transactionsFrom")
                        .HasForeignKey("fromWalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.session", "session")
                        .WithOne("transaction")
                        .HasForeignKey("ScholaAi.Models.transaction", "sessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholaAi.Models.wallet", "toWallet")
                        .WithMany("transactionsTo")
                        .HasForeignKey("toWalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("fromWallet");

                    b.Navigation("session");

                    b.Navigation("toWallet");
                });

            modelBuilder.Entity("ScholaAi.Models.user", b =>
                {
                    b.HasOne("ScholaAi.Models.applicationUser", "applicationUser")
                        .WithOne("UserProfile")
                        .HasForeignKey("ScholaAi.Models.user", "applicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("applicationUser");
                });

            modelBuilder.Entity("ScholaAi.Models.wallet", b =>
                {
                    b.HasOne("ScholaAi.Models.user", "user")
                        .WithOne("wallet")
                        .HasForeignKey("ScholaAi.Models.wallet", "userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ScholaAi.Models.applicationUser", b =>
                {
                    b.Navigation("UserProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("ScholaAi.Models.session", b =>
                {
                    b.Navigation("notifications");

                    b.Navigation("rating");

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("ScholaAi.Models.sessionRequest", b =>
                {
                    b.Navigation("adminLogs");

                    b.Navigation("requestBroadcasts");

                    b.Navigation("session");
                });

            modelBuilder.Entity("ScholaAi.Models.student", b =>
                {
                    b.Navigation("requests");

                    b.Navigation("sessions");
                });

            modelBuilder.Entity("ScholaAi.Models.subject", b =>
                {
                    b.Navigation("sessionRequests");

                    b.Navigation("teachers");
                });

            modelBuilder.Entity("ScholaAi.Models.teacher", b =>
                {
                    b.Navigation("ratings");

                    b.Navigation("requestBroadcasts");

                    b.Navigation("sessionRequests");

                    b.Navigation("sessions");
                });

            modelBuilder.Entity("ScholaAi.Models.user", b =>
                {
                    b.Navigation("adminLogs");

                    b.Navigation("admins");

                    b.Navigation("receivedMessages");

                    b.Navigation("receivedNotifications");

                    b.Navigation("sentMessages");

                    b.Navigation("sentNotifications");

                    b.Navigation("student");

                    b.Navigation("teacher");

                    b.Navigation("wallet");
                });

            modelBuilder.Entity("ScholaAi.Models.wallet", b =>
                {
                    b.Navigation("transactionsFrom");

                    b.Navigation("transactionsTo");
                });
#pragma warning restore 612, 618
        }
    }
}
